# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeowners < Formula
  desc "Determine who owns what according CODEOWNERS files"
  homepage "https://github.com/hmarr/codeowners"
  version "1.2.1"

  on_macos do
    on_intel do
      url "https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_darwin_amd64.tar.gz"
      sha256 "39d5868f50a3716af61c1bd4722b9f840f07a005d3018b20483de26b10ced19a"

      def install
        bin.install "codeowners"
      end
    end
    on_arm do
      url "https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_darwin_arm64.tar.gz"
      sha256 "1a271d2a3960491d7fceffdca741e7a3830cb2ab5013723ed8f9efe04dd3d9c1"

      def install
        bin.install "codeowners"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_linux_amd64.tar.gz"
        sha256 "94f9f9ec43dba151816b5c2fd98698afbfd03d5ac63db77d2d8c2cf77b326bb0"

        def install
          bin.install "codeowners"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_linux_arm64.tar.gz"
        sha256 "bb3a283e2bd6c50d8b383c5a8b99179ded65eefdbd95945826a61f860ce531f4"

        def install
          bin.install "codeowners"
        end
      end
    end
  end
end
