# This file was generated by GoReleaser. DO NOT EDIT.
class Codeowners < Formula
  desc "Determine who owns what according CODEOWNERS files"
  homepage "https://github.com/hmarr/codeowners"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hmarr/codeowners/releases/download/v0.2.0/codeowners_0.2.0_darwin_amd64.tar.gz"
    sha256 "b7ff3e5d425c973e158c93e1d619cdce3121d422882c7280d69997512138514d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hmarr/codeowners/releases/download/v0.2.0/codeowners_0.2.0_linux_amd64.tar.gz"
      sha256 "bd6051be7cf813c5c9a59140ac3a1ec7e80af8cc32a7d7502db583dd7361529a"
    end
  end

  def install
    bin.install "codeowners"
  end
end
